-- SpokenSubtitles -- the zone lore the recordings speak.
--
-- Spoken Zones keeps its lore in its private namespace, so this addon carries its own copy
-- (Data/Zones_<locale>.lua, generated by tools/build_zone_text.py). Only English -- the
-- language every pack falls back to -- and the client's own language are kept in memory;
-- the other files return at their first line.

local _, ns = ...
ns = ns or {}

local ZoneText = { byLocale = {} }
ns.ZoneText = ZoneText

local function ClientLocale()
    local locale = GetLocale and GetLocale() or "enUS"
    return locale == "enGB" and "enUS" or locale
end

function ZoneText:Wants(locale)
    return locale == "enUS" or locale == ClientLocale()
end

function ZoneText:Register(locale, entries)
    self.byLocale[locale] = entries
end

--- The text for a clip key: in the language the clip was recorded in when known, else the
--- client's, else English.
function ZoneText:Get(key, language)
    for _, locale in ipairs({ language or "", ClientLocale(), "enUS" }) do
        local entries = self.byLocale[locale]
        if entries and entries[key] then
            return entries[key], locale
        end
    end
    return nil
end

return ZoneText
