"""Generate SpokenSubtitles/Data/Zones_<locale>.lua from Spoken Zones' lore data.

Spoken Zones keeps its lore in its private addon namespace, so the subtitles carry their own
copy of the one field the recordings speak: `full` (measured: the zone recordings run at
~13.5 characters per second of `full`, and ~2 of `short`). Keys are the clip keys Spoken
Zones gives its lines: "z:<mapID>" for a zone, "s:<mapID>:<areaKey>" for a subzone.

    python tools/build_zone_text.py [path to a SpokenZones folder]

The default source is the installed addon, so the text matches the recordings on this
machine. For a release, point it at the SpokenZones folder of the Spoken version it targets.
Lore text is from warcraft.wiki.gg (CC BY-SA 4.0) except entries written for Spoken; the
generated files say so.
"""
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "SpokenSubtitles" / "Data"
DEFAULT_SOURCE = pathlib.Path(
    "C:/Program Files (x86)/World of Warcraft/_classic_beta_/Interface/AddOns/SpokenZones")
FALLBACK_LUPA = pathlib.Path.home() / "AppData/Local/Temp/opencode/spoken-verification-runtime"

try:
    import lupa.lua51 as lupa
except ImportError:
    sys.path.insert(0, str(FALLBACK_LUPA))
    import lupa.lua51 as lupa


def lua_string(text):
    text = text.replace("\r", "")
    return '"' + text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def load_locale(source, locale):
    lua = lupa.LuaRuntime(unpack_returned_tuples=True)
    lua.execute("""
        SZ = { data = {} }
        function SZ:ShouldLoadLanguage() return true end
        function SZ:RegisterLoreData(lang, kind, t) self.data[kind] = t end
    """)
    for kind in ("Zones", "Subzones"):
        path = (source / "Data" / locale / f"{kind}.lua").as_posix()
        lua.execute(f'assert(loadfile("{path}"))("SpokenZones", SZ)')
    entries = {}
    zones = lua.eval("SZ.data.zones") or {}
    for map_id, entry in zones.items():
        full = entry["full"] if entry else None
        if full:
            entries[f"z:{int(map_id)}"] = full
    subzones = lua.eval("SZ.data.subzones") or {}
    for map_id, areas in subzones.items():
        for key, entry in areas.items():
            full = entry["full"] if entry else None
            if full:
                entries[f"s:{int(map_id)}:{key}"] = full
    return entries


def main():
    source = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_SOURCE
    toc = next(source.glob("SpokenZones*.toc"), None)
    version = "unknown"
    if toc:
        for line in toc.read_text(encoding="utf-8").splitlines():
            if line.startswith("## Version:"):
                version = line.split(":", 1)[1].strip()
    OUT.mkdir(parents=True, exist_ok=True)
    locales = sorted(p.name for p in (source / "Data").iterdir()
                     if p.is_dir() and (p / "Zones.lua").exists())
    written = []
    for locale in locales:
        entries = load_locale(source, locale)
        lines = [
            f"-- AUTO-GENERATED by tools/build_zone_text.py from Spoken Zones {version}. Do not edit.",
            "--",
            "-- Lore text from warcraft.wiki.gg, licensed CC BY-SA 4.0, except where Spoken wrote",
            "-- an entry itself. Only `full`, the text the recordings speak, keyed by clip key.",
            "",
            "local _, ns = ...",
            f'if not (ns.ZoneText and ns.ZoneText:Wants("{locale}")) then return end',
            "",
            f'ns.ZoneText:Register("{locale}", {{',
        ]
        for key in sorted(entries):
            lines.append(f"\t[{lua_string(key)}] = {lua_string(entries[key])},")
        lines.append("})")
        path = OUT / f"Zones_{locale}.lua"
        path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
        written.append((locale, len(entries), path.stat().st_size))
    for locale, count, size in written:
        print(f"{locale}: {count} entries, {size // 1024} KB")
    print("source:", source, "version", version)
    return written


if __name__ == "__main__":
    main()
